

use_sim_time: false

slam_toolbox:
  mode: "mapping"              # mapping mode; change to "localization" if reusing a map later
  base_frame: "base_link"       # change if your robot uses a different base frame name
  odom_frame: "odom"
  map_frame: "map"
  
  # Laser scan topic
  scan_topic: "/scan"
  
  # Mapping parameters (tweak these for your environment)
  resolution: 0.05              # map resolution in meters per pixel
  publish_period: 1.0           # seconds between map publishes
  pose_update_min_d: 0.1        # minimum linear movement (m) before updating pose
  pose_update_min_a: 0.05       # minimum angular movement (radians) before updating pose
  
  # Beam parameters
  max_beam_range: 12.0          # maximum valid range (m)
  min_beam_range: 0.1           # minimum valid range (m)
  
  # Additional parameters can be added here as needed.
